################################################################################
# Manuscript: Single-cell whole-genome sequencing reveals convergent evolution in Burkitt lymphoma
# Description: latency correlations
# Author: Alexander Steemers
################################################################################

# Load libraries
library(readxl)
library(dplyr)
library(ggplot2)
source('Data/theme_burkitt.R')

# Load data
df <- read_excel("Data/latency_period.xlsx") # this file was generated by taking the data from the Ultrametric_*.R scripts

# Exponential model (log-linear): log(mut rate) ~ Age
df <- df %>% mutate(log_mut_rate = log(Mut_rate_tumour_mean))
exp_lm_mut_age <- lm(log_mut_rate ~ Age, data = df)

# Stats for annotation
r2_exp_age  <- summary(exp_lm_mut_age)$r.squared
p_age       <- summary(exp_lm_mut_age)$coefficients["Age", "Pr(>|t|)"]
p_str_age <- ifelse(p_age < 1e-4, "< 0.0001", sprintf("%.4f", p_age))

# Prediction grid over Age range
x_min_age <- min(df$Age, na.rm = TRUE)
x_max_age <- max(df$Age, na.rm = TRUE)
newdata_age <- data.frame(Age = seq(x_min_age, x_max_age, length.out = 200))
pred_age    <- predict(exp_lm_mut_age, newdata_age, interval = "confidence")

curve_df_age <- newdata_age %>%
  mutate(
    fit = exp(pred_age[, "fit"]),
    lwr = exp(pred_age[, "lwr"]),
    upr = exp(pred_age[, "upr"])
  )

# Axes (same y-scale as before)
y_min <- 0
y_max <- 350

# Annotation placement
ann_x_age <- x_max_age - 2
ann_y_age <- y_max * 0.80

# Plot
p_age_mut_age <- ggplot(df, aes(x = Age, y = Mut_rate_tumour_mean)) +
  geom_point(size = 3, color = "black", na.rm = TRUE) +
  geom_ribbon(
    data = curve_df_age,
    aes(x = Age, ymin = lwr, ymax = upr),
    inherit.aes = FALSE, alpha = 0.20
  ) +
  geom_line(
    data = curve_df_age,
    aes(x = Age, y = fit),
    inherit.aes = FALSE, color = "black", linewidth = 1
  ) +
  annotate(
    "text",
    x = ann_x_age, y = ann_y_age, hjust = 0, size = 5,
    label = paste0("R² = ", sprintf("%.3f", r2_exp_age), "\n",
                   "p = ", p_str_age)
  ) +
  labs(
    x = "Age at sampling (years)",
    y = "Mean tumour mutation rate post-expansion (SBS/year)"
  ) +
  scale_x_continuous(limits = c(x_min_age, x_max_age)) +
  scale_y_continuous(limits = c(y_min, y_max), breaks = seq(y_min, y_max, 50)) +
  theme_CHemALL() +
  theme(
    axis.text = element_text(size = 14),
    axis.title = element_text(size = 16),
    panel.grid.major.y = element_blank(),
    panel.grid.minor.y = element_blank()
  )

print(p_age_mut_age)

# # Save PDF
# ggsave(
#   filename = "mut_rate_post_MRCA_sample_age.pdf",
#   plot = p_age_mut_age,
#   width = 8, height = 6
# )

# Linear model: mutation rate ~ Age
lin_lm_mut_age <- lm(Mut_rate_tumour_mean ~ Age, data = df)

# Stats for annotation
r2_lin_age <- summary(lin_lm_mut_age)$r.squared
p_lin_age  <- summary(lin_lm_mut_age)$coefficients["Age", "Pr(>|t|)"]
p_str_lin_age <- ifelse(p_lin_age < 1e-4, "< 0.0001", sprintf("%.4f", p_lin_age))

# Prediction grid over Age range
x_min_age <- min(df$Age, na.rm = TRUE)
x_max_age <- max(df$Age, na.rm = TRUE)
newdata_age_lin <- data.frame(Age = seq(x_min_age, x_max_age, length.out = 200))
pred_age_lin    <- predict(lin_lm_mut_age, newdata_age_lin, interval = "confidence")
curve_df_age_lin <- cbind(newdata_age_lin, as.data.frame(pred_age_lin))

# Axes
y_min <- 0
y_max <- 350

# Annotation placement
ann_x_age <- x_max_age - 2
ann_y_age <- y_max * 0.80

# Plot (linear)
p_age_mut_lin <- ggplot(df, aes(x = Age, y = Mut_rate_tumour_mean)) +
  geom_point(size = 3, color = "black", na.rm = TRUE) +
  
  # 95% confidence ribbon
  geom_ribbon(
    data = curve_df_age_lin,
    aes(x = Age, ymin = lwr, ymax = upr),
    inherit.aes = FALSE,
    alpha = 0.20
  ) +
  
  # Linear regression line
  geom_line(
    data = curve_df_age_lin,
    aes(x = Age, y = fit),
    inherit.aes = FALSE,
    color = "black",
    linewidth = 1
  ) +
  
  # Annotation
  annotate(
    "text",
    x = ann_x_age, y = ann_y_age, hjust = 0, size = 5,
    label = paste0("R² = ", sprintf("%.3f", r2_lin_age), "\n",
                   "p = ", p_str_lin_age)
  ) +
  
  labs(
    x = "Age at sampling (years)",
    y = "Mean tumour mutation rate post-expansion (SBS/year)"
  ) +
  scale_x_continuous(limits = c(x_min_age, x_max_age)) +
  scale_y_continuous(limits = c(y_min, y_max), breaks = seq(y_min, y_max, 50)) +
  theme_CHemALL() +
  theme(
    axis.text = element_text(size = 14),
    axis.title = element_text(size = 16),
    panel.grid.major.y = element_blank(),
    panel.grid.minor.y = element_blank()
  )

print(p_age_mut_lin)

# Fit exponential model: log(Latency)

df <- df %>% mutate(log_latency = log(Latency_period))
exp_lm_lat_age <- lm(log_latency ~ Age, data = df)

# Stats for annotation

r2_age  <- summary(exp_lm_lat_age)$r.squared
p_age   <- summary(exp_lm_lat_age)$coefficients["Age", "Pr(>|t|)"]
p_age_str <- ifelse(p_age < 1e-5, "< 0.00001", sprintf("%.5f", p_age))

# Prediction range

x_min_age <- min(df$Age, na.rm = TRUE)
x_max_age <- max(df$Age, na.rm = TRUE)

new_age <- data.frame(Age = seq(x_min_age, x_max_age, length.out = 200))
pred_age <- predict(exp_lm_lat_age, new_age, interval = "confidence")

curve_df_age <- new_age %>%
  mutate(
    fit = exp(pred_age[, "fit"]),
    lwr = exp(pred_age[, "lwr"]),
    upr = exp(pred_age[, "upr"])
  )

# Y-axis limits for latency

y_min_lat <- 0
y_max_lat <- max(df$Latency_period) * 2

# Annotation placement

ann_x_age <- x_max_age - 2
ann_y_age <- y_max_lat * 0.85

# Plot

p_age_lat_age_exp <- ggplot(df, aes(x = Age, y = Latency_period)) +
  geom_point(size = 3, color = "black", na.rm = TRUE) +
  
  geom_ribbon(
    data = curve_df_age,
    aes(x = Age, ymin = lwr, ymax = upr),
    inherit.aes = FALSE,
    alpha = 0.2
  ) +
  geom_line(
    data = curve_df_age,
    aes(x = Age, y = fit),
    inherit.aes = FALSE,
    color = "black",
    linewidth = 1
  ) +
  annotate("text",
           x = ann_x_age, y = ann_y_age, hjust = 0, size = 5,
           label = paste0("R² = ", sprintf("%.3f", r2_age), "\n",
                          "p = ", p_age_str)
  ) +
  labs(
    x = "Age at sampling (years)",
    y = "Latency period (years)"
  ) +
  scale_x_continuous(limits = c(x_min_age, x_max_age)) +
  scale_y_continuous(limits = c(y_min_lat, y_max_lat)) +
  theme_CHemALL() +
  theme(
    axis.text = element_text(size = 14),
    axis.title = element_text(size = 16),
    panel.grid.major.y = element_blank(),
    panel.grid.minor.y = element_blank()
  )

print(p_age_lat_age_exp)

# # Save PDF
# ggsave(
#   filename = "latency_vs_age.pdf",
#   plot = p_age_lat_age_exp,
#   width = 8, height = 6
# )

# Linear model: Latency ~ Age
lin_lm_lat_age <- lm(Latency_period ~ Age, data = df)

# Stats
r2_age_lin <- summary(lin_lm_lat_age)$r.squared
p_age_lin  <- summary(lin_lm_lat_age)$coefficients["Age", "Pr(>|t|)"]
p_age_lin_str <- ifelse(p_age_lin < 1e-3, "< 0.001", sprintf("%.3f", p_age_lin))

# Predictions over plotting range
new_age_lin <- data.frame(Age = seq(x_min_age, x_max_age, length.out = 200))
pred_age_lin <- predict(lin_lm_lat_age, new_age_lin, interval = "confidence")
curve_df_age_lin <- cbind(new_age_lin, as.data.frame(pred_age_lin))

# Plot (linear)
p_age_lat_age_lin <- ggplot(df, aes(x = Age, y = Latency_period)) +
  geom_point(size = 3, color = "black", na.rm = TRUE) +
  geom_ribbon(
    data = curve_df_age_lin,
    aes(x = Age, ymin = lwr, ymax = upr),
    inherit.aes = FALSE, alpha = 0.2
  ) +
  geom_line(
    data = curve_df_age_lin,
    aes(x = Age, y = fit),
    inherit.aes = FALSE, color = "black", linewidth = 1
  ) +
  annotate(
    "text",
    x = ann_x_age, y = ann_y_age, hjust = 0, size = 5,
    label = paste0("R² = ", sprintf("%.3f", r2_age_lin), "\n",
                   "p = ", p_age_lin_str)
  ) +
  labs(
    x = "Age at sampling (years)",
    y = "Latency period (years)"
  ) +
  scale_x_continuous(limits = c(x_min_age, x_max_age)) +
  scale_y_continuous(limits = c(y_min_lat, y_max_lat)) +
  theme_CHemALL() +
  theme(
    axis.text = element_text(size = 14),
    axis.title = element_text(size = 16),
    panel.grid.major.y = element_blank(),
    panel.grid.minor.y = element_blank()
  )

print(p_age_lat_age_lin)

AIC(exp_lm_mut_age, lin_lm_mut_age)
AIC(exp_lm_lat_age, lin_lm_lat_age)